### ISSUE TITLE
Only works when logged out 

### ISSUE THREAD

**Issue by Findus23** [piwik/plugin-TreemapVisualization#10]
When I am logged in I only see an empty box.
![screenshot_20170413_104422](https://cloud.githubusercontent.com/assets/6266037/24997265/48efe606-2036-11e7-86d2-971f365d7d08.png)

The dropdown menu still works but I can't change it back to the normal tables.

There are also no javascript errors.

**Comment by Findus23** [comment]
That's odd. I force reloaded the page and got an grey box:
![screenshot_20170413_104733](https://cloud.githubusercontent.com/assets/6266037/24997364/adf149dc-2036-11e7-917e-5f6dac6dab8f.png)

But switching to an table and back to the treemap makes it work again.

**Comment by sgiehl** [comment]
Which browser are you using? Will try to reproduce that tomorrow when I have some time.

**Comment by Findus23** [comment]
I am using chromium, but a test in Firefox shows the exact same error. (At first nothing, the empty box after a force reload (and at every reload afterwards) and the correct treemap after changing visualisation.

If it helps: The URL requested when the gray box appers is:
```url
http://localhost/piwik/index.php?module=DevicesDetection&action=getBrowsers&idSite=1&period=month&date=today&showtitle=1&random=7773
```
and when it's working it is:
```url
http://localhost/piwik/index.php?date=today&viewDataTable=infoviz-treemap&availableWidth=450&availableHeight=320&columns=nb_visits&module=DevicesDetection&action=getBrowsers&idSite=1&period=month&random=7773
```

**Comment by sgiehl** [comment]
@Findus23 could you please confirm this issue is fixed?

**Comment by Findus23** [comment]
It's working now, but I found a new issue similar to #11 (will mention it there)
