### ISSUE TITLE
Setting parameters rows_to_display is not allowed.

### ISSUE THREAD

**Issue by Findus23** [piwik/plugin-TreemapVisualization#11]
When I try to click on a folder in the `Pages`-Overview, nothing happens.
The request 
`http://localhost/piwik/index.php?date=today&viewDataTable=infoviz-treemap&availableWidth=450&availableHeight=875&columns=nb_hits&module=API&action=index&idSite=1&period=month&random=0&filter_offset=0&enable_filter_excludelowpop=0&idSubtable=1&method=TreemapVisualization.getTreemapData&apiMethod=Actions.getPageUrls&format=json&column=nb_hits&show_evolution_values=1` 
returns 500 and the following error appears in the server log:

`PHP message: Error in Piwik: Setting parameters rows_to_display is not allowed. Please report this bug to the Piwik team`

**Comment by sgiehl** [comment]
I'm able to reproduce. But I'm getting `{"result":"error","message":"Class 'Piwik\\Plugins\\TreemapVisualization\\Treemap' not found"}` as direct error response for the request

**Comment by sgiehl** [comment]
@Findus23 could you please check if the fix I've committed fixes it for you as well?

**Comment by Findus23** [comment]
It's now working for me.

**Comment by Findus23** [comment]
The treemaps work for Browsers and OS. But when I change the view to "unique visiors" or "users", the box stays gray and again I get `Setting parameters rows_to_display is not allowed.` on the following request:

```http
POST /piwik/index.php?date=2017-04-15&module=CoreHome&action=saveViewDataTableParameters&report_id=DevicesDetection.getBrowsers&idSite=1&period=month HTTP/1.1
Host: localhost
Connection: keep-alive
Content-Length: 202
Accept: text/html, */*; q=0.01
Origin: http://localhost
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
DNT: 1
Referer: http://localhost/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
Accept-Encoding: gzip, deflate, br
Accept-Language: de-AT,de-DE;q=0.8,de;q=0.6,en-US;q=0.4,en;q=0.2
Cookie: piwik_auth=login%3Dczo1OiJhZG1pbiI7%3Atoken_auth%3DczozMjoiNDI1NzYyYWVmMzc1N2NjMmRmNzAzNDI1OGIzZmE5MDYiOw%3D%3D%3A_%3D11f48d07b522f670da3a878aabadc21944b87d9e; _xsrf=2|e60ea3c0|efc82b42a3768fc772cfea5b9ccf5966|1491823921; username-localhost-8888="2|1:0|10:1491823927|23:username-localhost-8888|44:YTUxNDY5NWFjNTE1NGYzYzhmMjA3MmM0ODJmNDRmODE=|3a7914a22870e11c572f0949b1f046573f1daa8d162efee20cdf761a5e7c3469"; PIWIK_SESSID=1p5bie3v26snpa23p1un6q2ih5
```
and POST argument "parameters" set to 
```json
{"columns":["nb_users"],"columns_to_display":["nb_users"],"rows":[],"rows_to_display":[]}
```

**Comment by sgiehl** [comment]
Could you please check if data for nb_users is available? Try switching to another view and have a look if nb_users is > 0. Otherwise it would be correct.

**Comment by Findus23** [comment]
While I can't find the `nb_users`, I guess you are right as the user report shows that there are no users. (I am using the visitorgenerator)
