### ISSUE TITLE
treemap error 

### ISSUE THREAD

**Issue by bamcguire** [piwik/plugin-TreemapVisualization#20]
I recently installed the treemap plugin for wordpress(version 5.4.1) current php.  The error I am recieving is as follows:

Warning: Use of undefined constant PIWIK_INCLUDE_PATH - assumed 'PIWIK_INCLUDE_PATH' (this will throw an Error in a future version of PHP) in /home/xxxxxxxxxx/public_html/wp-content/plugins/TreemapVisualization/TreemapVisualization.php on line 28

Warning: require_once(PIWIK_INCLUDE_PATH/plugins/TreemapVisualization/Visualizations/Treemap.php): failed to open stream: No such file or directory in /home/xxxxxxxxxx/public_html/wp-content/plugins/TreemapVisualization/TreemapVisualization.php on line 28

Fatal error: require_once(): Failed opening required 'PIWIK_INCLUDE_PATH/plugins/TreemapVisualization/Visualizations/Treemap.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/xxxxxxxxxx/public_html/wp-content/plugins/TreemapVisualization/TreemapVisualization.php on line 28

**Comment by tsteur** [comment]
Thanks for mentioning this issue @bamcguire 

I've just released version 3.1.2 which includes a fix for this.

**Comment by bamcguire** [comment]
confirming bug fix, and thank you!
