### ISSUE TITLE
Setting parameters rows_to_display is not allowed

### ISSUE THREAD

**Issue by Findus23** [piwik/plugin-TreemapVisualization#23]
> Error in Matomo: Setting parameters rows_to_display is not allowed. Please report this bug to the Matomo team.

when changing the metric to display

**Comment by sgiehl** [comment]
I guess the choose-able metrics are actually not the metrics that are available for the report. Which report did you try it with?

**Comment by Findus23** [comment]
I was looking at the `Device type` report.

![grafik](https://user-images.githubusercontent.com/6266037/96740179-e0bc0880-13c0-11eb-852f-744c2869cbc0.png)

**Comment by sgiehl** [comment]
Ah ok. Switching the metric actually works, but the error occurs when Matomo tries to store the changed viewDataTable settings...

**Comment by sgiehl** [comment]
That's actually a global issue in Matomo. It also happens when choosing other metrics in bar charts.
