### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by comradekingu** [piwik/plugin-TreemapVisualization#26]
This plugin isn't translatable like the others
https://hosted.weblate.org/projects/matomo/

https://github.com/matomo-org/plugin-TreemapVisualization/blob/4.x-dev/screenshots/Social_Network_Treemap.png should also be "GitHub".

**Comment by Findus23** [comment]
I am not sure if this plugin contains translatable strings. It at least doesn't contain a lang/ directory

**Comment by sgiehl** [comment]
@comradekingu As @Findus23 mentioned, this plugin does not have any translatable parts. Everything it displays is data provided by other plugins.
And the `Github` actually comes from our test data and should be written correctly otherwise.
