### ISSUE TITLE
Cannot translate the plugin

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/plugin-TreemapVisualization#27]
Hi guys,

I cannot find it on weblate, I guess it is not possible to translate this plugin so far.
Could you please make that possible?

Thank you,

**Comment by sgiehl** [comment]
@Chardonneaur The plugin actually has not translations, as there is not much that could be translated. The only thing I could think of would be word `Treemap` it self and maybe the plugin description.

**Comment by Chardonneaur** [comment]
Yes, exactly, so far one cannot translate the meta description of the plugin.
