### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [piwik/plugin-TreemapVisualization#30]
https://hosted.weblate.org/projects/matomo/plugin-treemapvisualization/nb_NO/#information
says LGPLv3, whereas https://github.com/matomo-org/plugin-TreemapVisualization/blob/4.x-dev/LICENSE
is GPLv3.

Can be changed in https://hosted.weblate.org/settings/matomo/plugin-treemapvisualization

**Comment by sgiehl** [comment]
Thanks for that. I've updated the license
