### ISSUE TITLE
Completely Broken on "Visits by Server Time"

### ISSUE THREAD

**Issue by drakej** [piwik/plugin-TreemapVisualization#4]
When I use this plugin visualization on the mentioned widget, it shows nothing but "Other". I don't see this behavior on other widgets (so far).

I'm running Piwik version 2.1.0 and TreemapVisualization version 1.0.10

**Comment by sgiehl** [comment]
This is not a bug in Treemap plugin. API method is not able to handle Datatable Maps. See referenced PR
