### ISSUE TITLE
Display Broken in 2.10.0

### ISSUE THREAD

**Issue by mixmatch** [piwik/plugin-TreemapVisualization#5]
Showing no colors, interface images seem to be from a theme (Zeitgeist) that is no longer used as well:
GET http://URL/piwik/plugins/Zeitgeist/images/zoom-out.png 404 (Not Found)

![treemap](https://cloud.githubusercontent.com/assets/7726889/6150650/ca42b7c6-b1cd-11e4-86cc-d31c65efca6f.png)

**Comment by mattab** [comment]
Hi @nixmatch - this should work in 2.15.0 and latest plugin, please try again
